workflows:
    ios-workflow:
      name: iOS Workflow
      environment:
        xcode: 15.4
        cocoapods: default
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Change iOS app name
          script: /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" -c "Set :CFBundleDisplayName $APP_NAME" ./swiftlabel/Info.plist
        - name: Set bundle id
          script: sed -i '' -e 's/PRODUCT_BUNDLE_IDENTIFIER \= [^\;]*\;/PRODUCT_BUNDLE_IDENTIFIER = '${BUNDLE_ID}';/' ./swiftlabel.xcodeproj/project.pbxproj
        - name: iOS code signing
          script: |
            keychain initialize
            app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
            keychain add-certificates
            xcode-project use-profiles
        - name: Install CocoaPods dependencies
          script: |
            pod install
        - name: Increment build number
          script: |
            # agvtool new-version -all $(($BUILD_NUMBER + 1))
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))

        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "swiftlabel.xcworkspace" --scheme "swiftlabel"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM


