workflows:
    ios-workflow:
      name: iOS Workflow
      integrations:
        app_store_connect: ${API_KEY_NAME}
      environment:
        ios_signing:
          distribution_type: app_store
          bundle_identifier: io.codemagic.swiftwhitelabel.dev
        xcode: 15.4
        cocoapods: default
        groups:
          - client_001
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Install CocoaPods dependencies
          script: |
            pod install
        - name: Increment build number
          script: |
            agvtool new-version -all $(($BUILD_NUMBER + 1))
            # agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))

        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      # publishing:
      #   app_store_connect:
      #     auth: integration 

